import json, os, math, logging, re

from clint.textui import progress

from uristmaps.config import conf
from uristmaps.filefinder import sites_and_pops


def load_populations():
    with open(os.path.join(conf.get("Paths", "build"), "sites.json")) as sitesjs:
        sites = json.loads(sitesjs.read())

    fname = sites_and_pops()

    # Regexpatterns
    id_find = re.compile("(\d+):")
    current_site = None

    popinfo = {}
    with open(fname, "r") as popsfile:
        #for line in progress.dots(popsfile, every=100):
        for line in popsfile:
            if line.startswith("Outdoor"):
                break
            match = id_find.match(line)
            if not match:
                if not current_site:
                    continue
                # Add the info to the current site
                add_pop_info(line, popinfo[current_site])
            else:
                # Found a starting line for a new site
                current_site = match.group(1)
                popinfo[current_site] = {}

    #print() # A very nice linebreak after all the dots generated by the loop

    for site in sites:
        site.update(popinfo[site["id"]])

    with open(os.path.join(conf.get("Paths", "build"), "sites.json"), "w") as sitesjson:
        sitesjson.write(json.dumps(sites))


def add_pop_info(line, site_dict):
    """ Add the info contained in the text line to the
    site dict.
    Line can be like on of these:
       Owner: Brodoshrukus, kobolds
       Parent Civ: Srubukulmus, kobolds
       118 kobolds
    """
    line = line.strip()
    if not line:
        return
    if ":" in line:
        split = line.split(":")
        site_dict[split[0]] = " ".join(split[1:])
    else:
        if "popinfo" not in site_dict:
            site_dict["popinfo"] = {}
        split = line.split(" ")
        site_dict["popinfo"][" ".join(split[1:])] = int(split[0])

